### ISSUE TITLE
Use Container Policy from SELinuxProject

### ISSUE THREAD

**Issue by patsys** [rancher/rke2-selinux#25]
Hello,

please implement with the Container Policy from https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/services/container.te

**Comment by dweomer** [comment]
The policy defined in this repo depends on [container-selinux policy](https://github.com/containers/container-selinux) available for each supported OS, e.g.:
- https://github.com/rancher/rke2-selinux/blob/v0.9.stable.1/policy/centos8/rke2-selinux.spec#L42

None of the supported OSes yet leverage container-specific policy from the selinux refpolicy:
- el7/el8 :arrow_right: [2.20091117](https://github.com/SELinuxProject/refpolicy/tree/RELEASE_2_20091117)
- sle/microos :arrow_right: (looks like it is copied from fedora, because of course it is. what a mess)

**Comment by JAORMX** [comment]
FWIW, Flatcar Linux is adopting the container SELinux policy from refpolicy.

**Comment by dweomer** [comment]
> FWIW, Flatcar Linux is adopting the container SELinux policy from refpolicy.

I am looking forward to seeing more modern SELinux installations that diverge from RedHat's.

**Comment by galal-hussein** [comment]
closing this issue since there is no-op is required from our side
